### ISSUE TITLE
Unable to Pair on iOS 15 beta 6

### ISSUE THREAD

**Issue by wardsimon** [openairplay/goplay2#29]
It seems like something has changed in the pairing mechanism for the latest iOS beta. On attempted casting the following is logged with an error `Unable to connect`: 
```
2021/08/24 18:50:45 request received : GET /info body 70
2021/08/24 18:50:45 response sent : body 374
2021/08/24 18:50:45 request received : POST /pair-verify body 37
2021/08/24 18:50:45 response sent : body 140
2021/08/24 18:50:45 request received : POST /pair-setup body 6
2021/08/24 18:50:45 response sent : body 409
2021/08/24 18:50:45 request received : POST /pair-setup body 457
2021/08/24 18:50:45 response sent : body 69
2021/08/24 18:50:45 request received : POST /pair-setup body 159
2021/08/24 18:50:45 response sent : body 143
2021/08/24 18:50:45 request received : POST /pair-verify body 37
2021/08/24 18:50:45 server.go:82: Error:Error handling RSTP request Invalid internal pairing verify step Waiting
```
When paired  through the home app there are no errors. However the following is in the log:
```
2021/08/24 18:57:20 request received : POST /configure body 148
2021/08/24 18:57:20 response sent : body 237
2021/08/24 18:57:20 request received : TEARDOWN rtsp://192.168.1.73/7350123517057450268 body 42
2021/08/24 18:57:20 response sent : body 0
2021/08/24 18:57:20 server.go:37: Error:Event error : EOF
2021/08/24 18:57:20 server.go:76: Error:Error parsing RSTP request EOF 
```
And the same error when trying to cast.

Casting works on iOS 14.7.1 and macOS devices.

**Comment by AlbanSeurat** [comment]
Thanks for the heads up. I will have a look

**Comment by noelhibbard** [comment]
Please tell me Apple isn't already trying to spoil the fun.

**Comment by AlbanSeurat** [comment]
It seems that there are issues with the Airplay 2 with other Apple Device (Airport Express / Apple TV).
I would wait to see if the final version has also some errors before trying to correct the possible bugs

**Comment by iChUdY** [comment]
Final iOS 15 is here and same problem:

2021/09/25 21:16:50 Starting goplay for device Pi: 35aa4396-8bb7-42e3-9e45-3803aecfdb90, guid: 35aa4396-8bb7-42e3-9e45-3803aecfdb90, Psi: 35aa4396-8bb7-42e3-9e45-3803aecfdb90
2021/09/25 21:17:04 request received : GET /info body 70
2021/09/25 21:17:04 response sent : body 374
2021/09/25 21:17:04 request received : POST /pair-verify body 37
2021/09/25 21:17:04 response sent : body 140
2021/09/25 21:17:04 request received : POST /pair-setup body 6
2021/09/25 21:17:04 response sent : body 409
2021/09/25 21:17:04 request received : POST /pair-setup body 457
2021/09/25 21:17:05 response sent : body 69
2021/09/25 21:17:05 request received : POST /pair-setup body 159
2021/09/25 21:17:05 response sent : body 143
2021/09/25 21:17:05 request received : POST /pair-verify body 37
2021/09/25 21:17:05 server.go:82: Error:Error handling RSTP request Invalid internal pairing verify step Waiting

**Comment by rainbowicenow** [comment]
Same with iOS 15.1 Public Beta 2
Adds to Home just fine at first, but needs to change the name when re-adding it to Home

2021/10/03 23:35:45 request received : GET /info body 70
2021/10/03 23:35:45 response sent : body 374
2021/10/03 23:35:45 request received : POST /pair-verify body 37
2021/10/03 23:35:45 response sent : body 140
2021/10/03 23:35:45 request received : POST /pair-verify body 37
2021/10/03 23:35:45 server.go:82: Error:Error handling RSTP request Invalid internal pairing verify step Waiting

**Comment by Neustradamus** [comment]
The iOS 15.0.x is now here, the problem is here too?

Note: The iOS 15.1 Beta 4 is here too.

**Comment by prashnts** [comment]
Curiously the python port still works fine (ish) with iOS15.

The only thing there that does not work is sync between my Sonos's Airplay (which seems to have longer delay).

And yes, happy to help if you need it, too!

**Comment by lucek8123** [comment]
## @AlbanSeurat Any way to pair GoPlay2 with iOS/iPadOS 15 and macOS Monterey?

Any upadates? I still having that problem. 

```2021/10/03 23:35:45 request received : GET /info body 70
2021/10/03 23:35:45 response sent : body 374
2021/10/03 23:35:45 request received : POST /pair-verify body 37
2021/10/03 23:35:45 response sent : body 140
2021/10/03 23:35:45 request received : POST /pair-verify body 37
2021/10/03 23:35:45 server.go:82: Error:Error handling RSTP request Invalid internal pairing verify step Waiting

**Comment by noelhibbard** [comment]
> ## @AlbanSeurat Any way to pair GoPlay2 with iOS/iPadOS 15 and macOS Monterey?
> Any upadates? I still having that problem.
> 
> ```
> 2021/10/03 23:35:45 response sent : body 374
> 2021/10/03 23:35:45 request received : POST /pair-verify body 37
> 2021/10/03 23:35:45 response sent : body 140
> 2021/10/03 23:35:45 request received : POST /pair-verify body 37
> 2021/10/03 23:35:45 server.go:82: Error:Error handling RSTP request Invalid internal pairing verify step Waiting
> ```

He seems to be busy on other obligations. Just curious, have you tried the development branch of shairport-sync? It has AirPlay 2 support and HomeKit pairing is working well with it. Even on iOS 15.2. It's stable enough that there is talk about merging AP2 into the master branch.

**Comment by lucek8123** [comment]
Hi, any changes?

**Comment by jasonkolodziej** [comment]
I am not on iOS 15 beta version, just normal but facing the same exact issues.

DEVICE: Raspberry PI ZERO W2

Running on Ubuntu Core 22.04 with a snap created for such.

I am trying out the feature/-- branch right now and will reply with updates.


btw if anyone would like the snapcraft.yaml file lmk :-)
![image](https://github.com/openairplay/goplay2/assets/42076058/59368c1e-76b9-413e-b635-644590749120)

**Comment by jasonkolodziej** [comment]
> I am not on iOS 15 beta version, just normal but facing the same exact issues.
> 
> DEVICE: Raspberry PI ZERO W2
> 
> Running on Ubuntu Core 22.04 with a snap created for such.
> 
> I am trying out the feature/-- branch right now and will reply with updates.
> 
> btw if anyone would like the snapcraft.yaml file lmk :-) ![image](https://private-user-images.githubusercontent.com/42076058/297891200-59368c1e-76b9-413e-b635-644590749120.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MTYwNjEsIm5iZiI6MTcwNTYxNTc2MSwicGF0aCI6Ii80MjA3NjA1OC8yOTc4OTEyMDAtNTkzNjhjMWUtNzZiOS00MTNlLWI2MzUtNjQ0NTkwNzQ5MTIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDIyMDkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4OGVlYzc0YTg0NDNmNWUwMDIzNDZlZjIxNGI3YWM0YjBhM2NhMThmNWMwMjZiZTc0ZGZlZjQ1ZTU2MzdmZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fGxDqxPgKhPrzBJrIifJubmwwL7_VZnRbUWUhBNgqG0)

Update for branch: feature/audio-sync


![image](https://github.com/openairplay/goplay2/assets/42076058/5ec3ca47-a406-4c12-aace-4223113cb71f)


I noticed that `audio/player.go` might need a `StreamCallback` for `audio.Player{}.stream` from `codec/stream.go` aka `codec.StreamCallback{}` instead of a new `codec.Stream{}`?

This was a fast take at debugging the feature branch... Not sure if that's the case?
