### ISSUE TITLE
Stopped working with iOS version 15.1

### ISSUE THREAD

**Issue by meta-n4vn33t** [openairplay/goplay2#35]
```
arya@Aryas-Mac-mini goplay2 % ./goplay2 -n Airplay2 -i en0
2021/10/27 13:10:07 Airplay2/config.json is not valid - at new file will be created at program exit
2021/10/27 13:10:07 Starting goplay for device Pi: bf832c73-77c2-47b5-9212-544192fb2a17, guid: bf832c73-77c2-47b5-9212-544192fb2a17, Psi: bf832c73-77c2-47b5-9212-544192fb2a17
2021/10/27 13:11:29 request received : GET /info body 70
2021/10/27 13:11:29 response sent : body 374
2021/10/27 13:11:29 request received : POST /pair-verify body 37
2021/10/27 13:11:29 response sent : body 140
2021/10/27 13:11:29 request received : POST /pair-setup body 6
2021/10/27 13:11:29 response sent : body 409
2021/10/27 13:11:29 request received : POST /pair-setup body 457
2021/10/27 13:11:29 response sent : body 69
2021/10/27 13:11:29 request received : POST /pair-setup body 159
2021/10/27 13:11:29 response sent : body 143
2021/10/27 13:11:29 request received : POST /pair-verify body 37
2021/10/27 13:11:29 server.go:82: Error:Error handling RSTP request Invalid internal pairing verify step Waiting
```
